### ISSUE TITLE
Can't find data file "adjacency_matrix.npy" and so on

### ISSUE THREAD

**Issue by Francis-Zheng** [TachiChan/IJCAI2019_HGAT#1]
Could you tell me how to get these data files? Data files provided by @guyulongcs are raw dataset ? should I generate *.npy files myself ?

**Comment by TachiChan** [comment]
The '*.npy' files are stored in JD Clusters. However, I finished my internship at JD in May this year. I write one script to generate random input files based on the required format, which can be run for testing.

```
import numpy as np

# PARAMS
NUM_USER = 1000
NUM_ITEM = 2000
NUM_WORD = 100
DIM_WORD = 200

NUM_SAMPLE_USER_1 = 10
NUM_SAMPLE_USER_2 = 4
NUM_SAMPLE_ITEM = 10
NUM_SAMPLE_WORD = 10

SIZE_ADJ_USER = NUM_SAMPLE_USER_1 + NUM_SAMPLE_USER_2 * NUM_SAMPLE_USER_1 + 1

# GENERATE
np.random.seed(1234567)
word_feature = np.random.rand(NUM_WORD, DIM_WORD)

adjacency_matrix = np.random.randint(NUM_USER, size=(NUM_USER, SIZE_ADJ_USER, SIZE_ADJ_USER))

vertex_id_ = np.random.randint(NUM_USER, size=(NUM_USER, SIZE_ADJ_USER-1))
ego_user_id = np.arange(NUM_USER).reshape(NUM_USER, 1)
vertex_id = np.concatenate((vertex_id_, ego_user_id), axis=1)

interaction_item = np.random.randint(NUM_ITEM, size=(NUM_USER, NUM_SAMPLE_ITEM))
interaction_word = np.random.randint(NUM_WORD, size=(NUM_ITEM, NUM_SAMPLE_WORD))

one_hot_gender = np.eye(2)
label_gender_ = np.random.randint(2, size=NUM_USER)
label_gender = one_hot_gender[label_gender_]

one_hot_age = np.eye(4)
label_age_ = np.random.randint(4, size=NUM_USER)
label_age = one_hot_age[label_age_]

# SAVE
np.save('word_feature.npy', word_feature)
np.save('adjacency_matrix.npy', adjacency_matrix)
np.save('vertex_id.npy', vertex_id)
np.save('interaction_item.npy', interaction_item)
np.save('interaction_word.npy', interaction_word)
np.save('label_gender.npy', label_gender)
np.save('label_age.npy', label_age)
```

**Comment by Francis-Zheng** [comment]
Thank you very much for your patience in providing the script ~ 

> The '*.npy' files are stored in JD Clusters. However, I finished my internship at JD in May this year. I write one script to generate random input files based on the required format, which can be run for testing.
> 
> ```
> import numpy as np
> 
> # PARAMS
> NUM_USER = 1000
> NUM_ITEM = 2000
> NUM_WORD = 100
> DIM_WORD = 200
> 
> NUM_SAMPLE_USER_1 = 10
> NUM_SAMPLE_USER_2 = 4
> NUM_SAMPLE_ITEM = 10
> NUM_SAMPLE_WORD = 10
> 
> SIZE_ADJ_USER = NUM_SAMPLE_USER_1 + NUM_SAMPLE_USER_2 * NUM_SAMPLE_USER_1 + 1
> 
> # GENERATE
> np.random.seed(1234567)
> word_feature = np.random.rand(NUM_WORD, DIM_WORD)
> 
> adjacency_matrix = np.random.randint(NUM_USER, size=(NUM_USER, SIZE_ADJ_USER, SIZE_ADJ_USER))
> 
> vertex_id_ = np.random.randint(NUM_USER, size=(NUM_USER, SIZE_ADJ_USER-1))
> ego_user_id = np.arange(NUM_USER).reshape(NUM_USER, 1)
> vertex_id = np.concatenate((vertex_id_, ego_user_id), axis=1)
> 
> interaction_item = np.random.randint(NUM_ITEM, size=(NUM_USER, NUM_SAMPLE_ITEM))
> interaction_word = np.random.randint(NUM_WORD, size=(NUM_ITEM, NUM_SAMPLE_WORD))
> 
> one_hot_gender = np.eye(2)
> label_gender_ = np.random.randint(2, size=NUM_USER)
> label_gender = one_hot_gender[label_gender_]
> 
> one_hot_age = np.eye(4)
> label_age_ = np.random.randint(4, size=NUM_USER)
> label_age = one_hot_age[label_age_]
> 
> # SAVE
> np.save('word_feature.npy', word_feature)
> np.save('adjacency_matrix.npy', adjacency_matrix)
> np.save('vertex_id.npy', vertex_id)
> np.save('interaction_item.npy', interaction_item)
> np.save('interaction_word.npy', interaction_word)
> np.save('label_gender.npy', label_gender)
> np.save('label_age.npy', label_age)
> ```

Thank you very much for your patience in providing the script ~

**Comment by Francis-Zheng** [comment]
> The '*.npy' files are stored in JD Clusters. However, I finished my internship at JD in May this year. I write one script to generate random input files based on the required format, which can be run for testing.
> 
> ```
> import numpy as np
> 
> # PARAMS
> NUM_USER = 1000
> NUM_ITEM = 2000
> NUM_WORD = 100
> DIM_WORD = 200
> 
> NUM_SAMPLE_USER_1 = 10
> NUM_SAMPLE_USER_2 = 4
> NUM_SAMPLE_ITEM = 10
> NUM_SAMPLE_WORD = 10
> 
> SIZE_ADJ_USER = NUM_SAMPLE_USER_1 + NUM_SAMPLE_USER_2 * NUM_SAMPLE_USER_1 + 1
> 
> # GENERATE
> np.random.seed(1234567)
> word_feature = np.random.rand(NUM_WORD, DIM_WORD)
> 
> adjacency_matrix = np.random.randint(NUM_USER, size=(NUM_USER, SIZE_ADJ_USER, SIZE_ADJ_USER))
> 
> vertex_id_ = np.random.randint(NUM_USER, size=(NUM_USER, SIZE_ADJ_USER-1))
> ego_user_id = np.arange(NUM_USER).reshape(NUM_USER, 1)
> vertex_id = np.concatenate((vertex_id_, ego_user_id), axis=1)
> 
> interaction_item = np.random.randint(NUM_ITEM, size=(NUM_USER, NUM_SAMPLE_ITEM))
> interaction_word = np.random.randint(NUM_WORD, size=(NUM_ITEM, NUM_SAMPLE_WORD))
> 
> one_hot_gender = np.eye(2)
> label_gender_ = np.random.randint(2, size=NUM_USER)
> label_gender = one_hot_gender[label_gender_]
> 
> one_hot_age = np.eye(4)
> label_age_ = np.random.randint(4, size=NUM_USER)
> label_age = one_hot_age[label_age_]
> 
> # SAVE
> np.save('word_feature.npy', word_feature)
> np.save('adjacency_matrix.npy', adjacency_matrix)
> np.save('vertex_id.npy', vertex_id)
> np.save('interaction_item.npy', interaction_item)
> np.save('interaction_word.npy', interaction_word)
> np.save('label_gender.npy', label_gender)
> np.save('label_age.npy', label_age)
> ```

Thank you very much for your patience in providing the script ~

**Comment by TachiChan** [comment]
It's my pleasure ~
